// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Multiple.proto

// Protobuf Java Version: 3.25.2
package top.sharehome.protobuf_demo0_init.pojo;

public final class Multiple {
  private Multiple() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultipleFactoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultipleFactory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * message第一个参数：用dataType来标识传的是哪个枚举类型
     * </pre>
     *
     * <code>.MultipleFactory.DateType dateType = 1;</code>
     * @return The enum numeric value on the wire for dateType.
     */
    int getDateTypeValue();
    /**
     * <pre>
     * message第一个参数：用dataType来标识传的是哪个枚举类型
     * </pre>
     *
     * <code>.MultipleFactory.DateType dateType = 1;</code>
     * @return The dateType.
     */
    top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType getDateType();

    /**
     * <code>.Boss boss = 2;</code>
     * @return Whether the boss field is set.
     */
    boolean hasBoss();
    /**
     * <code>.Boss boss = 2;</code>
     * @return The boss.
     */
    top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss getBoss();
    /**
     * <code>.Boss boss = 2;</code>
     */
    top.sharehome.protobuf_demo0_init.pojo.Multiple.BossOrBuilder getBossOrBuilder();

    /**
     * <code>.Worker worker = 3;</code>
     * @return Whether the worker field is set.
     */
    boolean hasWorker();
    /**
     * <code>.Worker worker = 3;</code>
     * @return The worker.
     */
    top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker getWorker();
    /**
     * <code>.Worker worker = 3;</code>
     */
    top.sharehome.protobuf_demo0_init.pojo.Multiple.WorkerOrBuilder getWorkerOrBuilder();

    top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   * protobuf可以使用message管理其他的message
   * </pre>
   *
   * Protobuf type {@code MultipleFactory}
   */
  public static final class MultipleFactory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MultipleFactory)
      MultipleFactoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultipleFactory.newBuilder() to construct.
    private MultipleFactory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultipleFactory() {
      dateType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MultipleFactory();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_MultipleFactory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_MultipleFactory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.class, top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.Builder.class);
    }

    /**
     * <pre>
     * 定义其他message的枚举类型，枚举不算是message中的正式参数，proto3要求枚举类型中枚举字段序号必须从 0 开始
     * </pre>
     *
     * Protobuf enum {@code MultipleFactory.DateType}
     */
    public enum DateType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BossType = 0;</code>
       */
      BossType(0),
      /**
       * <code>WorkerType = 1;</code>
       */
      WorkerType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BossType = 0;</code>
       */
      public static final int BossType_VALUE = 0;
      /**
       * <code>WorkerType = 1;</code>
       */
      public static final int WorkerType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DateType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DateType forNumber(int value) {
        switch (value) {
          case 0: return BossType;
          case 1: return WorkerType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DateType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DateType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DateType>() {
              public DateType findValueByNumber(int number) {
                return DateType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.getDescriptor().getEnumTypes().get(0);
      }

      private static final DateType[] VALUES = values();

      public static DateType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DateType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MultipleFactory.DateType)
    }

    private int dataBodyCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      BOSS(2),
      WORKER(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return BOSS;
          case 3: return WORKER;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATETYPE_FIELD_NUMBER = 1;
    private int dateType_ = 0;
    /**
     * <pre>
     * message第一个参数：用dataType来标识传的是哪个枚举类型
     * </pre>
     *
     * <code>.MultipleFactory.DateType dateType = 1;</code>
     * @return The enum numeric value on the wire for dateType.
     */
    @java.lang.Override public int getDateTypeValue() {
      return dateType_;
    }
    /**
     * <pre>
     * message第一个参数：用dataType来标识传的是哪个枚举类型
     * </pre>
     *
     * <code>.MultipleFactory.DateType dateType = 1;</code>
     * @return The dateType.
     */
    @java.lang.Override public top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType getDateType() {
      top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType result = top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType.forNumber(dateType_);
      return result == null ? top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType.UNRECOGNIZED : result;
    }

    public static final int BOSS_FIELD_NUMBER = 2;
    /**
     * <code>.Boss boss = 2;</code>
     * @return Whether the boss field is set.
     */
    @java.lang.Override
    public boolean hasBoss() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Boss boss = 2;</code>
     * @return The boss.
     */
    @java.lang.Override
    public top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss getBoss() {
      if (dataBodyCase_ == 2) {
         return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_;
      }
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance();
    }
    /**
     * <code>.Boss boss = 2;</code>
     */
    @java.lang.Override
    public top.sharehome.protobuf_demo0_init.pojo.Multiple.BossOrBuilder getBossOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_;
      }
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance();
    }

    public static final int WORKER_FIELD_NUMBER = 3;
    /**
     * <code>.Worker worker = 3;</code>
     * @return Whether the worker field is set.
     */
    @java.lang.Override
    public boolean hasWorker() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.Worker worker = 3;</code>
     * @return The worker.
     */
    @java.lang.Override
    public top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker getWorker() {
      if (dataBodyCase_ == 3) {
         return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_;
      }
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance();
    }
    /**
     * <code>.Worker worker = 3;</code>
     */
    @java.lang.Override
    public top.sharehome.protobuf_demo0_init.pojo.Multiple.WorkerOrBuilder getWorkerOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_;
      }
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dateType_ != top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType.BossType.getNumber()) {
        output.writeEnum(1, dateType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dateType_ != top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType.BossType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dateType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory)) {
        return super.equals(obj);
      }
      top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory other = (top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory) obj;

      if (dateType_ != other.dateType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getBoss()
              .equals(other.getBoss())) return false;
          break;
        case 3:
          if (!getWorker()
              .equals(other.getWorker())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATETYPE_FIELD_NUMBER;
      hash = (53 * hash) + dateType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + BOSS_FIELD_NUMBER;
          hash = (53 * hash) + getBoss().hashCode();
          break;
        case 3:
          hash = (37 * hash) + WORKER_FIELD_NUMBER;
          hash = (53 * hash) + getWorker().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * protobuf可以使用message管理其他的message
     * </pre>
     *
     * Protobuf type {@code MultipleFactory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultipleFactory)
        top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_MultipleFactory_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_MultipleFactory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.class, top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.Builder.class);
      }

      // Construct using top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dateType_ = 0;
        if (bossBuilder_ != null) {
          bossBuilder_.clear();
        }
        if (workerBuilder_ != null) {
          workerBuilder_.clear();
        }
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_MultipleFactory_descriptor;
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory getDefaultInstanceForType() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.getDefaultInstance();
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory build() {
        top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory buildPartial() {
        top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory result = new top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dateType_ = dateType_;
        }
      }

      private void buildPartialOneofs(top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory result) {
        result.dataBodyCase_ = dataBodyCase_;
        result.dataBody_ = this.dataBody_;
        if (dataBodyCase_ == 2 &&
            bossBuilder_ != null) {
          result.dataBody_ = bossBuilder_.build();
        }
        if (dataBodyCase_ == 3 &&
            workerBuilder_ != null) {
          result.dataBody_ = workerBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory) {
          return mergeFrom((top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory other) {
        if (other == top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.getDefaultInstance()) return this;
        if (other.dateType_ != 0) {
          setDateTypeValue(other.getDateTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case BOSS: {
            mergeBoss(other.getBoss());
            break;
          }
          case WORKER: {
            mergeWorker(other.getWorker());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                dateType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getBossFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getWorkerFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dateType_ = 0;
      /**
       * <pre>
       * message第一个参数：用dataType来标识传的是哪个枚举类型
       * </pre>
       *
       * <code>.MultipleFactory.DateType dateType = 1;</code>
       * @return The enum numeric value on the wire for dateType.
       */
      @java.lang.Override public int getDateTypeValue() {
        return dateType_;
      }
      /**
       * <pre>
       * message第一个参数：用dataType来标识传的是哪个枚举类型
       * </pre>
       *
       * <code>.MultipleFactory.DateType dateType = 1;</code>
       * @param value The enum numeric value on the wire for dateType to set.
       * @return This builder for chaining.
       */
      public Builder setDateTypeValue(int value) {
        dateType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * message第一个参数：用dataType来标识传的是哪个枚举类型
       * </pre>
       *
       * <code>.MultipleFactory.DateType dateType = 1;</code>
       * @return The dateType.
       */
      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType getDateType() {
        top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType result = top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType.forNumber(dateType_);
        return result == null ? top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * message第一个参数：用dataType来标识传的是哪个枚举类型
       * </pre>
       *
       * <code>.MultipleFactory.DateType dateType = 1;</code>
       * @param value The dateType to set.
       * @return This builder for chaining.
       */
      public Builder setDateType(top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory.DateType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dateType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * message第一个参数：用dataType来标识传的是哪个枚举类型
       * </pre>
       *
       * <code>.MultipleFactory.DateType dateType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dateType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss, top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.Builder, top.sharehome.protobuf_demo0_init.pojo.Multiple.BossOrBuilder> bossBuilder_;
      /**
       * <code>.Boss boss = 2;</code>
       * @return Whether the boss field is set.
       */
      @java.lang.Override
      public boolean hasBoss() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Boss boss = 2;</code>
       * @return The boss.
       */
      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss getBoss() {
        if (bossBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_;
          }
          return top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return bossBuilder_.getMessage();
          }
          return top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance();
        }
      }
      /**
       * <code>.Boss boss = 2;</code>
       */
      public Builder setBoss(top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss value) {
        if (bossBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          bossBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Boss boss = 2;</code>
       */
      public Builder setBoss(
          top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.Builder builderForValue) {
        if (bossBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          bossBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Boss boss = 2;</code>
       */
      public Builder mergeBoss(top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss value) {
        if (bossBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance()) {
            dataBody_ = top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.newBuilder((top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            bossBuilder_.mergeFrom(value);
          } else {
            bossBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Boss boss = 2;</code>
       */
      public Builder clearBoss() {
        if (bossBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          bossBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Boss boss = 2;</code>
       */
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.Builder getBossBuilder() {
        return getBossFieldBuilder().getBuilder();
      }
      /**
       * <code>.Boss boss = 2;</code>
       */
      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.BossOrBuilder getBossOrBuilder() {
        if ((dataBodyCase_ == 2) && (bossBuilder_ != null)) {
          return bossBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_;
          }
          return top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance();
        }
      }
      /**
       * <code>.Boss boss = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss, top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.Builder, top.sharehome.protobuf_demo0_init.pojo.Multiple.BossOrBuilder> 
          getBossFieldBuilder() {
        if (bossBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance();
          }
          bossBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss, top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.Builder, top.sharehome.protobuf_demo0_init.pojo.Multiple.BossOrBuilder>(
                  (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();
        return bossBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker, top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.Builder, top.sharehome.protobuf_demo0_init.pojo.Multiple.WorkerOrBuilder> workerBuilder_;
      /**
       * <code>.Worker worker = 3;</code>
       * @return Whether the worker field is set.
       */
      @java.lang.Override
      public boolean hasWorker() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.Worker worker = 3;</code>
       * @return The worker.
       */
      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker getWorker() {
        if (workerBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_;
          }
          return top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return workerBuilder_.getMessage();
          }
          return top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance();
        }
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder setWorker(top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker value) {
        if (workerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          workerBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder setWorker(
          top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.Builder builderForValue) {
        if (workerBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          workerBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder mergeWorker(top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker value) {
        if (workerBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance()) {
            dataBody_ = top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.newBuilder((top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            workerBuilder_.mergeFrom(value);
          } else {
            workerBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder clearWorker() {
        if (workerBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          workerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.Builder getWorkerBuilder() {
        return getWorkerFieldBuilder().getBuilder();
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.WorkerOrBuilder getWorkerOrBuilder() {
        if ((dataBodyCase_ == 3) && (workerBuilder_ != null)) {
          return workerBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_;
          }
          return top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance();
        }
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker, top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.Builder, top.sharehome.protobuf_demo0_init.pojo.Multiple.WorkerOrBuilder> 
          getWorkerFieldBuilder() {
        if (workerBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance();
          }
          workerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker, top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.Builder, top.sharehome.protobuf_demo0_init.pojo.Multiple.WorkerOrBuilder>(
                  (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();
        return workerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MultipleFactory)
    }

    // @@protoc_insertion_point(class_scope:MultipleFactory)
    private static final top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory();
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultipleFactory>
        PARSER = new com.google.protobuf.AbstractParser<MultipleFactory>() {
      @java.lang.Override
      public MultipleFactory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MultipleFactory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultipleFactory> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.sharehome.protobuf_demo0_init.pojo.Multiple.MultipleFactory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BossOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Boss)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Boss}
   */
  public static final class Boss extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Boss)
      BossOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Boss.newBuilder() to construct.
    private Boss(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Boss() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Boss();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Boss_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Boss_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.class, top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss)) {
        return super.equals(obj);
      }
      top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss other = (top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Boss}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Boss)
        top.sharehome.protobuf_demo0_init.pojo.Multiple.BossOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Boss_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Boss_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.class, top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.Builder.class);
      }

      // Construct using top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Boss_descriptor;
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss getDefaultInstanceForType() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance();
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss build() {
        top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss buildPartial() {
        top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss result = new top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss) {
          return mergeFrom((top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss other) {
        if (other == top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Boss)
    }

    // @@protoc_insertion_point(class_scope:Boss)
    private static final top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss();
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Boss>
        PARSER = new com.google.protobuf.AbstractParser<Boss>() {
      @java.lang.Override
      public Boss parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Boss> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Boss> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.sharehome.protobuf_demo0_init.pojo.Multiple.Boss getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WorkerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Worker)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string bossName = 2;</code>
     * @return The bossName.
     */
    java.lang.String getBossName();
    /**
     * <code>string bossName = 2;</code>
     * @return The bytes for bossName.
     */
    com.google.protobuf.ByteString
        getBossNameBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Worker}
   */
  public static final class Worker extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Worker)
      WorkerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Worker.newBuilder() to construct.
    private Worker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Worker() {
      bossName_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Worker();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Worker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Worker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.class, top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int BOSSNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bossName_ = "";
    /**
     * <code>string bossName = 2;</code>
     * @return The bossName.
     */
    @java.lang.Override
    public java.lang.String getBossName() {
      java.lang.Object ref = bossName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bossName_ = s;
        return s;
      }
    }
    /**
     * <code>string bossName = 2;</code>
     * @return The bytes for bossName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBossNameBytes() {
      java.lang.Object ref = bossName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bossName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bossName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bossName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bossName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bossName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker)) {
        return super.equals(obj);
      }
      top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker other = (top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) obj;

      if (getId()
          != other.getId()) return false;
      if (!getBossName()
          .equals(other.getBossName())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + BOSSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBossName().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Worker}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Worker)
        top.sharehome.protobuf_demo0_init.pojo.Multiple.WorkerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Worker_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.class, top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.Builder.class);
      }

      // Construct using top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        bossName_ = "";
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker getDefaultInstanceForType() {
        return top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance();
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker build() {
        top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker buildPartial() {
        top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker result = new top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bossName_ = bossName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker) {
          return mergeFrom((top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker other) {
        if (other == top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getBossName().isEmpty()) {
          bossName_ = other.bossName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                bossName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bossName_ = "";
      /**
       * <code>string bossName = 2;</code>
       * @return The bossName.
       */
      public java.lang.String getBossName() {
        java.lang.Object ref = bossName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bossName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bossName = 2;</code>
       * @return The bytes for bossName.
       */
      public com.google.protobuf.ByteString
          getBossNameBytes() {
        java.lang.Object ref = bossName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bossName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bossName = 2;</code>
       * @param value The bossName to set.
       * @return This builder for chaining.
       */
      public Builder setBossName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bossName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string bossName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBossName() {
        bossName_ = getDefaultInstance().getBossName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string bossName = 2;</code>
       * @param value The bytes for bossName to set.
       * @return This builder for chaining.
       */
      public Builder setBossNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bossName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Worker)
    }

    // @@protoc_insertion_point(class_scope:Worker)
    private static final top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker();
    }

    public static top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Worker>
        PARSER = new com.google.protobuf.AbstractParser<Worker>() {
      @java.lang.Override
      public Worker parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Worker> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Worker> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.sharehome.protobuf_demo0_init.pojo.Multiple.Worker getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultipleFactory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultipleFactory_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Boss_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Boss_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Worker_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Worker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/Multiple.proto\"\246\001\n\017MultipleFacto" +
      "ry\022+\n\010dateType\030\001 \001(\0162\031.MultipleFactory.D" +
      "ateType\022\025\n\004boss\030\002 \001(\0132\005.BossH\000\022\031\n\006worker" +
      "\030\003 \001(\0132\007.WorkerH\000\"(\n\010DateType\022\014\n\010BossTyp" +
      "e\020\000\022\016\n\nWorkerType\020\001B\n\n\010dataBody\" \n\004Boss\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"4\n\006Worker\022\n\n\002i" +
      "d\030\001 \001(\005\022\020\n\010bossName\030\002 \001(\t\022\014\n\004name\030\003 \001(\tB" +
      "4\n&top.sharehome.protobuf_demo0_init.poj" +
      "oB\010MultipleH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MultipleFactory_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MultipleFactory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultipleFactory_descriptor,
        new java.lang.String[] { "DateType", "Boss", "Worker", "DataBody", });
    internal_static_Boss_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Boss_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Boss_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Worker_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Worker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Worker_descriptor,
        new java.lang.String[] { "Id", "BossName", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
